condense_wildcard_suffixes = true
empty_item_single_line = false
error_on_line_overflow = true
format_code_in_doc_comments = true
format_macro_matchers = true
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
max_width = 120
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
struct_lit_single_line = false
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
